### ISSUE TITLE
Expand test suite

### ISSUE THREAD

**Issue by jimeh** [jimeh/tmuxifier#49]
As of #46 there's a decent test framework/skeleton and some basic tests added, but more are needed.
### Todo

Below is an overview of things in need of tests along with the current test status.
- [x] Basic test framework setup.
- [ ] Main `tmuxifier` executable in bin folder.
- [ ] Files in lib folder:
  - [x] env.sh
  - [ ] layout-helpers.sh:
    - [x] tmux()
    - [x] new_window()
    - [ ] split_v()
    - [ ] split_h()
    - [ ] split_vl()
    - [ ] split_hl()
    - [ ] clock()
    - [x] select_window()
    - [ ] select_pane()
    - [ ] send_keys()
    - [ ] run_cmd()
    - [ ] session_root()
    - [ ] window_root()
    - [ ] load_window()
    - [ ] load_session()
    - [ ] initialize_session()
    - [ ] finalize_and_go_to_session()
    - [x] __expand_path()
    - [x] __get_first_window_index()
    - [x] __get_current_window_index()
    - [x] __go_to_session()
    - [x] __go_to_window_or_session_path()
  - [x] runtime.sh
  - [x] util.sh
- [ ] Files in libexec folder:
  - [ ] tmuxifier-alias
  - [ ] tmuxifier-commands
  - [ ] tmuxifier-completions
  - [ ] tmuxifier-current-session
  - [ ] tmuxifier-edit-session
  - [ ] tmuxifier-edit-window
  - [ ] tmuxifier-help
  - [ ] tmuxifier-init
  - [ ] tmuxifier-list
  - [ ] tmuxifier-list-sessions
  - [ ] tmuxifier-list-windows
  - [ ] tmuxifier-load-session
  - [ ] tmuxifier-load-window
  - [ ] tmuxifier-new-session
  - [ ] tmuxifier-new-window
  - [ ] tmuxifier-resolve-command-path
  - [x] tmuxifier-tmux
  - [ ] tmuxifier-tmux-version
  - [ ] tmuxifier-version
